config/routes.rb
Snaptrivia::Application.routes.draw do

  resources :questions, :subjects, :messages

  get 'game_home/gameHome'
  get 'questions/new'
  get 'game/ask_question'
  get 'game/challenge'
  get 'game/index'
  get 'game/cancel_transaction'
  get 'game/success_transaction'
  get 'game/game' => 'game#game'
  get 'game/new'
  get 'game/question_results'
  get 'game/end_game'
  get 'game/use_power_up_skip_question'
  get 'game/use_power_up_remove_wrong_answer'
  get 'game/use_power_up_extra_time'
  get 'statistics/show'
  get 'statistics/index'

  get 'statistics/site_stats'

  get 'challenge/question_results', to: 'game#question_results'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "game/rules"
  get "game/welcome"

  devise_for :reviewers
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

   root 'game#index'

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  CORRECT = 'CORRECT'
  INCORRECT = 'INCORRECT'
  EXTRA_TIME = 'extra_time'
  REMOVE_WRONG_ANSWERS = 'remove_wrong_answers'
  SKIP_QUESTION = 'skip_question'
  DIFFICULTY_LOW = 1
  DIFFICULTY_MEDIUM = 2
  DIFFICULTY_HIGH = 3
  DIFFICULTY_LEVELS = [DIFFICULTY_LOW, DIFFICULTY_MEDIUM, DIFFICULTY_HIGH]
  EASY = 'easy'
  MEDIUM = 'medium'
  HARD = 'hard'
  NONE = 'none'
  RATINGS = [EASY, MEDIUM, HARD, NONE]
  CHANGE_THRESHOLD = 60
  RATINGS_THRESHOLD = 10

  #has_one :subject
  #accepts_nested_attributes_for :subject
  belongs_to :user

  validates :title, presence: true
  validates :rightAns, presence: true
  validates :wrongAns1, presence: true
  validates :wrongAns2, presence: true
  validates :wrongAns3, presence: true
  validates :subject_title, presence: true


  # Gets question by subject
  def self.question_by_subject(sub)
    @question = Question.where("questions.subject_title" => sub)
  end

  def self.questions_by_subject(subject)
    @questions = Question.where(subject_title: subject)
  end

  def self.random_question_by_subject(subject)
    questions = self.question_by_subject(subject)
    questions.offset(rand(questions.count)).first
  end

  def self.random_question_id(subject)
    question = Question.random_question_by_subject(subject)
    question.id
  end

  def self.random_question_random_subject
    random_subject = Subject::subjects.sample
    @question = self.random_question_by_subject(random_subject)
  end

  def self.questions_by_difficulty(level, subject, quantity)
    if level != DIFFICULTY_LOW && level != DIFFICULTY_MEDIUM && level != DIFFICULTY_HIGH
      fail 'Invalid difficulty level'
    elsif !Subject.subject_valid?(subject)
      fail 'Invalid subject'
    elsif !quantity.integer?
      fail 'Invalid quantity'
    else
      @questions = Question.where(difficulty: level, subject_title: subject).limit(quantity)
    end
  end

  def self.questions_by_user_experience(experience_level, subject)
    if !User.experience_levels.include?(experience_level)
      fail 'Invalid experience level'
    elsif !Subject.subject_valid?(subject)
        fail 'Invalid subject'
    else
      if experience_level == User::BEGINNER
        @user_questions = questions_by_difficulty(DIFFICULTY_LOW, subject, 3)
        @user_questions += questions_by_difficulty(DIFFICULTY_MEDIUM, subject, 1)
        @user_questions.shuffle!
      elsif experience_level == User::INTERMEDIATE
        @user_questions = questions_by_difficulty(DIFFICULTY_MEDIUM, subject, 3)
        @user_questions += questions_by_difficulty(DIFFICULTY_LOW, subject, 1)
        @user_questions.shuffle!
      elsif experience_level == User::ADVANCED
        @user_questions = questions_by_difficulty(DIFFICULTY_MEDIUM, subject, 3)
        @user_questions += questions_by_difficulty(DIFFICULTY_HIGH, subject, 1)
        @user_questions.shuffle!
      else
        @user_questions = questions_by_difficulty(DIFFICULTY_HIGH, subject, 3)
        @user_questions += questions_by_difficulty(DIFFICULTY_MEDIUM, subject, 1)
        @user_questions.shuffle!
      end
    end
  end

  def apply_rating(rating)
    if RATINGS.include?(rating)
      case rating
        when EASY
          count = self.easy_ratings + 1
          self.update_attributes!(easy_ratings: count)
          self.save!
          true
        when MEDIUM
          count = self.medium_ratings + 1
          self.update_attributes!(medium_ratings: count)
          self.save!
          true
        when HARD
          count = self.hard_ratings + 1
          self.update_attributes!(hard_ratings: count)
          self.save!
          true
        else
          false
      end
    else
      fail 'Invalid rating.'
    end
  end

  def fifty_fifty
    [self.rightAns, self.wrongAns1]
  end

  def check_rating
    current_ratings = ratings_for_difficulty
    other_ratings = other_ratings_indexer
    total_ratings = other_ratings.reduce(:+)
    if total_ratings >= RATINGS_THRESHOLD
      other_ratings.each { |o|
        if o > current_ratings
          change = fractional_change(current_ratings, o)
          if change > CHANGE_THRESHOLD
            self.approved = false
            self.save!
            notify_reviewers_ratings
            return true
          end
        end
      }
    else
      false
    end
  end

  def ratings_for_difficulty
    ratings.fetch(self.difficulty - 1)
  end

  # TODO TEST, THEN MAKE METHOD PRIVATE
  def fractional_change(current_ratings, other_ratings)
    difference = current_ratings - other_ratings
    if other_ratings == 0
      return 0
    else
      change = Rational(difference.abs, other_ratings)
      Rational(change.to_f * 100).round
    end
  end

  private

  def ratings
    [self.easy_ratings, self.medium_ratings, self.hard_ratings]
  end

  def other_ratings_indexer
    return [0, 0, self.medium_ratings, self.hard_ratings] if self.difficulty == DIFFICULTY_LOW
    return [0, self.easy_ratings, 0, self.hard_ratings] if self.difficulty == DIFFICULTY_MEDIUM
    [0, self.easy_ratings, self.medium_ratings, 0] if self.difficulty == DIFFICULTY_HIGH
  end

  def notify_reviewers_ratings
    subject = "Question Approval Status Changed"
    body = "Please do not reply to this message. It has been generated by the system.\n\n" +
        "More than 60% of the ratings for this question are for a different difficulty level. \n" +
        "Please take some time to review its difficulty setting. \n\n" +
        "Thank you,\n\n" +
        "System Administrator\n\n"
    payload = self.id
    Reviewer.notify_reviewers(subject, body, payload)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # gets all questions sets to @questions
  def index
    @questions = Question.all
  end

  # shows question only for display
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end


  def new
  end

  # creates new question checks params
  def create

    @question = Question.new(question_params)
    @question.save
    if @question.valid?
      Reviewer.notify_reviewers('New Question', @question.title, @question.id)
      flash[:notice] = 'Reviewers have been notified. Your question is pending'
    else
      flash[:alert] = 'Please fill out all the fields and try again.'
    end
    redirect_to new_question_path
  end

  # private check for params
  private
  def question_params
    params.require(:question).permit(:id, :title, :rightAns, :wrongAns1, :wrongAns2, :wrongAns3, :subject_title, :approved, :difficulty, :user_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/new.html.erb
<header>
  <%= stylesheet_link_tag "rules", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</header>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">

      <body>

      <h1>New Question</h1>



      <%= form_for :question, url: questions_path do |f| %><br/>
          <h4>Subject</h4>

          <p>
            <%= f.collection_select(:subject_title, Subject.all, :subject_title, :subject_title ) %>
          </p>


          <h4>Difficulty</h4>
          <p>
            <%= f.select(:difficulty) do %>
            <% [[Question::EASY, Question::DIFFICULTY_LOW],[Question::MEDIUM, Question::DIFFICULTY_MEDIUM],[Question::HARD, Question::DIFFICULTY_HIGH]].each do |d|  %>
                <%= content_tag(:option, d.first, value: d.last) %>
                    <% end %>
            <% end %>
          </p>

          <%= f.hidden_field :user_id, :value => current_user.id %>

          <p>
            <%= f.label :Question %><br>
            <%= f.text_area :title %>
          </p>

          <h2>Answers:</h2>

          <p>
            <%= f.label :Correct%><br>
            <%= f.text_area :rightAns %>
          </p>

          <p>
            <%= f.label :InCorrect %><br>
            <%= f.text_area :wrongAns1 %>
          </p>

          <p>
            <%= f.label :InCorrect %><br>
            <%= f.text_area :wrongAns2 %>
          </p>

          <p>
            <%= f.label :InCorrect %><br>
            <%= f.text_area :wrongAns3 %>
          </p>

          <p>
            <%= f.submit %>
          </p>
          </body>
      <% end %>

      </div>
  </div>
</div>

app/views/questions/show.html.erb
<%
   question = @question
   answers = [question.rightAns, question.wrongAns1, question.wrongAns2, question.wrongAns3]
   answers = answers.shuffle
   correct_ans_index = answers.index(question.rightAns)
%>
<div style="display: none;">
  <p id="correct_ans"><%= correct_ans_index %></p>
</div>



<div class="container-fluid bg-info">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <!--        <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 200px;">
                    <span class="sr-only">60% Complete</span>
                  </div>
                </div>   -->

        <div class="progress progress-striped active">
          <div class="bar" style="width: 0%;"></div>
        </div>

        <h3><span class="label label-warning" id="qid"><%= @question.subject_title %></span>  <%= @question.title %></h3>
      </div>
      <div class="modal-body">
        <div class="col-xs-3 col-xs-offset-5">
          <div id="loadbar" style="display: none;">
            <div class="blockG" id="rotateG_01"></div>
            <div class="blockG" id="rotateG_02"></div>
            <div class="blockG" id="rotateG_03"></div>
            <div class="blockG" id="rotateG_04"></div>
            <div class="blockG" id="rotateG_05"></div>
            <div class="blockG" id="rotateG_06"></div>
            <div class="blockG" id="rotateG_07"></div>
            <div class="blockG" id="rotateG_08"></div>
          </div>
        </div>

        <div class="quiz" id="quiz" data-toggle="buttons">
          <label class="element-animation1 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="0"><%= answers[0] %></label>
          <label class="element-animation2 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="1"><%= answers[1] %></label>
          <label class="element-animation3 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="2"><%= answers[2] %></label>
          <label class="element-animation4 btn btn-lg btn-primary btn-block"><span class="btn-label"><i class="glyphicon glyphicon-chevron-right"></i></span> <input type="radio" name="q_answer" value="3"><%= answers[3] %></label>
        </div>
      </div>
      <div class="modal-footer text-muted">
        <span id="answer"></span>
      </div>
    </div>
  </div>
</div>

<script>


    $(document).ready(function(){

        var progress = setInterval(function() {
            var $bar = $('.bar');

            if ($bar.width()==400) {
                clearInterval(progress);
                $('.progress').removeClass('active');
            } else {
                $bar.width($bar.width()+40);
            }
            $bar.text($bar.width()/4 + "%");
        }, 800);

    });

    $(function(){
        var loading = $('#loadbar').hide();
        $(document)
                .ajaxStart(function () {
                    loading.show();
                }).ajaxStop(function () {
                    loading.hide();
                });

        $("label.btn").on('click',function () {
            var choice = $(this).find('input:radio').val();
            $('#loadbar').show();
            $('#quiz').fadeOut();
            setTimeout(function(){
                $( "#answer" ).html(  $(this).checking(choice) );
                $('#quiz').show();
                $('#loadbar').fadeOut();
                /* something else */
            }, 1500);
        });

        $ans = document.getElementById("correct_ans").innerHTML;

        $.fn.checking = function(ck) {
            if (ck != $ans)
                return 'INCORRECT';
            else
                return 'CORRECT';
        };
    });


</script>