config/routes.rb
Snaptrivia::Application.routes.draw do

  resources :questions, :subjects, :messages

  get 'game_home/gameHome'
  get 'questions/new'
  get 'game/ask_question'
  get 'game/challenge'
  get 'game/index'
  get 'game/cancel_transaction'
  get 'game/success_transaction'
  get 'game/game' => 'game#game'
  get 'game/new'
  get 'game/question_results'
  get 'game/end_game'
  get 'game/use_power_up_skip_question'
  get 'game/use_power_up_remove_wrong_answer'
  get 'game/use_power_up_extra_time'
  get 'statistics/show'
  get 'statistics/index'

  get 'statistics/site_stats'

  get 'challenge/question_results', to: 'game#question_results'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "game/rules"
  get "game/welcome"

  devise_for :reviewers
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

   root 'game#index'

  

end

app/models/message.rb
class Message < ActiveRecord::Base
  SYSTEM_ID = 0
  SYSTEM_NAME = 'System'
  READ = 1
  UNREAD = 0

  #validates_presence_of :subject, :body, :recipient_id
  validates :subject, length: { minimum: 3, maximum: 35 }
  validates :body, length: { minimum: 1, maximum: 1000 }

  belongs_to :user

  #################################
  ########  CLASS METHODS  ########
  #################################

  def self.recipient_list(user_id)
    User.where.not(id: user_id).where.not(provider: User::INACTIVE)
  end

  def self.send_system_message(recipient_id, subject, body, payload)
    @recipient = User.find(recipient_id)
    @message = Message.create({ sender_id: SYSTEM_ID, sender_name: SYSTEM_NAME, recipient_id: @recipient.id, recipient_name: @recipient.name, subject: subject, body: body, payload: payload })
    @message.save
  end

  def self.send_message(sender_id, recipient_id, subject, body)
    @sender = User.find(sender_id)
    @recipient = User.find(recipient_id)
    @message = Message.create({ sender_id: @sender.id, sender_name: @sender.name, recipient_id: @recipient.id, recipient_name: @recipient.name, subject: subject, body: body })
    @message.save!
  end

  def self.sent_messages_by_user_id(user_id)
    Message.where(sender_id: user_id)
  end

  def self.received_messages_by_user_id(user_id)
    Message.where(recipient_id: user_id)
  end

  def self.user_messages(user_id)
    sent_messages_by_user_id(user_id) + received_messages_by_user_id(user_id)
  end

  def self.unread_messages_by_user_id(user_id)
    received_messages_by_user_id(user_id).select {|message| message.recipient_read == UNREAD}
  end

  def self.read_messages_by_user_id(user_id)
    received_messages_by_user_id(user_id).select {|message| message.recipient_read == READ}
  end

  ###############################
  ######  INSTANCE METHODS  #####
  ###############################

  def mark_as_read(user_id)
    self.update_attributes!(sender_read: READ) if user_id == self.sender_id
    self.update_attributes!(recipient_read: READ) if user_id == self.recipient_id
    self.save!
  end

  def read_by_sender?
    self.sender_read == READ
  end

  def read_by_recipient?
    self.recipient_read == READ
  end

  ############################################################
  #####################     PRIVATE     ######################
  ############################################################

  private

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @user = current_user
    @unread_messages = Message.unread_messages_by_user_id(@user.id)
    @sent_messages = Message.sent_messages_by_user_id(@user.id)
    @read_messages = Message.read_messages_by_user_id(@user.id)
    respond_to do |format|
      format.html
    end
  end

  def show
    @message = Message.find(params[:id])
    @user = current_user
    if (@user.id == @message.sender_id) || (@user.id == @message.recipient_id)
    else
      respond_to do |format|
        format.html { redirect_to :action => :index, notice: 'No message found' }
      end
    end
  end

  def new
    @user_options = Message.recipient_list(current_user.id).all.map{|u| [ u.name, u.id ] }
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @message.sender_name = current_user.name
    @message.recipient_name = User.find(@message.recipient_id).name
    @message.read = Message::UNREAD
    @message.save
    respond_to do |format|
      if @message.save
        format.html { redirect_to :action => :index, notice: 'Message has been sent.' }
      else
        format.html { redirect_to :action => :new, notice: 'Error: Please try again.' }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end

  ############################################################
  #####################     PRIVATE     ######################
  ############################################################

  private

  def message_params
    params.require(:message).permit(:subject, :body, :sender_id, :recipient_id, :read, :sender_name, :recipient_name, :payload)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def marked_as_read(message)
    if @message.read != 1
      @message.read = 1
      @message.save
    end
  end

end

app/views/messages/_form.html.erb
<%= form_for @message do |form| %>
    <%= form.label :recipient_id %><br/>
    <%= form.select(:recipient_id, @user_options) %><br/>
    <%= form.label :subject %><br/>
    <%= form.text_field :subject %><br/>
    <%= form.label :body %><br/>
    <%= form.text_area :body %><br/>
    <%= form.submit 'Send message' %>
<% end %>

app/views/messages/_index.html.erb
<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%= render 'messages/unread' %>
    <%= render 'messages/read' %>
    <%= render 'messages/sent' %>
    </tbody>
  </table>
  <%= link_to 'Send new message', new_message_path %>
</div>

app/views/messages/_message.html.erb
<link href="/assets/stylesheets/bootstrap.css" rel="stylesheet">
<table class="table">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Sender</th>
    <th>Date</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= link_to message.subject, message_path(message) %></td>
    <td><%= message.sender_name %></td>
    <td><%= message.created_at %></td>
  </tr>
  </tbody>
</table>

app/views/messages/_new.html.erb
<div class="container">
  <h2>New message</h2>
  <%= render 'form' %>
  <%= link_to 'Back', messages_path %>
</div>

app/views/messages/_read.html.erb
<tr>
  <td><strong>Read Messages</strong></td>
  <td></td>
  <td></td>
</tr>
<% if @read_messages.any? %>
    <tr>
      <td><strong>Subject</strong></td>
      <td><strong>From</strong></td>
      <td><strong>Date</strong></td>
    </tr>
    <% @read_messages.each do |m| %>
        <tr>
          <td><%= link_to m.subject, message_path(m) %></td>
          <td><%= m.sender_name %></td>
          <td><%= m.created_at %></td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td>You have no read messages.</td>
      <td></td>
      <td></td>
    </tr>
<% end %>

app/views/messages/_sent.html.erb
<tr>
  <td><strong>Sent Messages</strong></td>
  <td></td>
  <td></td>
</tr>
<% if @sent_messages.any? %>
    <tr>
      <td><strong>Subject</strong></td>
      <td><strong>From</strong></td>
      <td><strong>Date</strong></td>
    </tr>
    <% @sent_messages.each do |m| %>
        <tr>
          <td><%= link_to m.subject, message_path(m) %></td>
          <td><%= m.sender_name %></td>
          <td><%= m.created_at %></td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td>You have no sent messages.</td>
      <td></td>
      <td></td>
    </tr>
<% end %>

app/views/messages/_show.html.erb
<div class="container">
  <% @message.mark_as_read(@user.id) %>
  <h3>Message</h3>
  <table class="table">
    <thead>
    <tr>
      <th>Subject</th>
      <th>From</th>
      <th>To</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @message.subject %></td>
      <td><%= @message.sender_name %></td>
      <td><%= @message.recipient_name %></td>
      <td><%= @message.created_at %></td>
    </tr>
    </tbody>
  </table>
  <h5><u>Message Body</u></h5>

  <p><%= @message.body %></p>
  <h5><u>Navigation</u></h5>
  <% if @user.admin && @message.sender_id != Message::SYSTEM_ID && @message.subject != 'New Question' %>
      <%= link_to 'View user in dashboard', rails_admin.show_path(model_name: 'user', id: @message.sender_id) %><br>
  <% end %>
  <% if @user.reviewer && @message.sender_id == Message::SYSTEM_ID %>
      <%= link_to 'View question in dashboard', rails_admin.show_path(model_name: 'question', id: @message.payload.to_i) %>
      <br>
  <% end %>
  <%= link_to 'Back', messages_path %>
</div>

app/views/messages/_unread.html.erb
<tr>
  <td><strong>Unread Messages</strong></td>
  <td></td>
  <td></td>
</tr>
<% if @unread_messages.any? %>
    <tr>
      <td><strong>Subject</strong></td>
      <td><strong>From</strong></td>
      <td><strong>Date</strong></td>
    </tr>
    <% @unread_messages.each do |m| %>
        <tr>
          <td><%= link_to m.subject, message_path(m) %></td>
          <td><%= m.sender_name %></td>
          <td><%= m.created_at %></td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td>You have no unread messages.</td>
      <td></td>
      <td></td>
    </tr>
<% end %>

app/views/messages/index.html.erb
<% if current_user %>
    <%= render 'messages/index' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>

app/views/messages/new.html.erb
<% if current_user %>
    <%= render 'messages/new' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>

app/views/messages/show.html.erb
<% if current_user %>
    <%= render 'messages/show' %>
<% else %>
    <% flash[:error] = "Unauthorized - The page is not available." %>
<%end%>