config/routes.rb
Snaptrivia::Application.routes.draw do

  resources :questions, :subjects, :messages

  get 'game_home/gameHome'
  get 'questions/new'
  get 'game/ask_question'
  get 'game/challenge'
  get 'game/index'
  get 'game/cancel_transaction'
  get 'game/success_transaction'
  get 'game/game' => 'game#game'
  get 'game/new'
  get 'game/question_results'
  get 'game/end_game'
  get 'game/use_power_up_skip_question'
  get 'game/use_power_up_remove_wrong_answer'
  get 'game/use_power_up_extra_time'
  get 'statistics/show'
  get 'statistics/index'

  get 'statistics/site_stats'

  get 'challenge/question_results', to: 'game#question_results'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "game/rules"
  get "game/welcome"

  devise_for :reviewers
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

   root 'game#index'

  

end

app/controllers/game_controller.rb
# noinspection ALL
class GameController < ApplicationController
  include GameHelper

  # Creates new game
  def new
    game_id = params[:game_id].to_i
    if game_id.to_i == 0
      @player2 = User.find(params[:player2_id])
      @game = Game.new(player1_id: current_user.id, player2_id: @player2.id, player1_turn: true, game_status: 'active',
                       art_trophy_p1: false, entertainment_trophy_p1: false, history_trophy_p1: false,
                       geography_trophy_p1: false, science_trophy_p1: false, sports_trophy_p1: false,
                       art_trophy_p2: false, entertainment_trophy_p2: false, history_trophy_p2: false,
                       geography_trophy_p2: false, science_trophy_p2: false, sports_trophy_p2: false)
      @game.save!
      @game_stat = GameStat.new(game_id: @game.id)
      @game_stat.save!
      back_to_game(@game.id)
    end
  end

  def index
    @active_games = Game.active_games_by_user(current_user.id)
    @finished_games = Game.finished_games_by_user(current_user.id)
    @playable_users = Game.playable_users(current_user.id)
    if current_user.unread_messages.count > 0
      flash.alert = 'You have unread messages'
    end

  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes!(params[:game])
    respond_to do |format|
      #format.html {redirect_to game_index_path}
      format.js
    end
  end

  # accepts game_id if 0 random user if 0 new game if game_id != 0  new game
  def game
    game_id = params[:game_id].to_i
    if game_id != 0
      @game = Game.find(game_id)
      unless @game.active?
        flash.notice = 'The game is over.'
        back_to_index
      end
      unless @game.players_turn?(current_user.id)
        back_to_index
      end
      @opponent = @game.opponent(current_user.id)
      if @game.challenge_round?
        ask_another_question(@game.id)
      end
    end
  end

  def end_game
    game_id = params[:game_id].to_i
    if game_id != 0
      @game = Game.find(game_id)
      if @game.active?
        @game.end_game(@game.opponent_id(current_user.id))
      else
        notice = 'The game already ended'
        if @game.winner_id == current_user.id
          notice += '. You won!'
        else
          notice += '.'
        end
        flash.notice = notice
      end
      back_to_index
    end
  end

  # Will challenge game stats for game
  def show
    @game = Game.find(params[:game_id])
  end

  # accepts result, game_id, and subject_title increments current_game.turn_count current_game.answers_correct
  # user.subject_total user_correct_questions
  def question_results
    result = params[:result]
    @result = result
    game_id = params[:game_id]
    subject = params[:subject_title]
    @current_game = Game.find(game_id)
    @current_game.save!

    if @current_game.active? && @current_game.players_turn?(current_user.id)
      @current_game.game_stat.apply_question_result(subject, result)
      applied_result = current_user.apply_question_results(subject, result)
      check_question_result(applied_result)
      if @current_game.normal_round?
        @bonus = params[:bonus]
        @current_game.bonus = @bonus
        game_result = @current_game.apply_to_normal_round(subject, current_user.id, @result)
        if game_result == Game::TIE
          @current_game.update_attributes(game_status: Game::ACTIVE, bonus: Game::BONUS_FALSE)
          @current_game.save
          wager = @current_game.get_wagerable_trophies(current_user.id).first
          prize = @current_game.get_winnable_trophies(current_user.id).first
          @challenge = Challenge.create_challenge(@current_game.id, current_user.id, @current_game.opponent_id(current_user.id), wager, prize)
          @challenge.save
          redirect_to game_ask_question_path and return
        end
        if @current_game.finished?
          current_user.apply_game_result(@current_game.id)
          @current_game.opponent(current_user.id).apply_game_result(@current_game.id)
          notify_game_outcome(@current_game)
          back_to_index and return
        elsif @current_game.players_turn?(current_user.id)
          back_to_game(@current_game.id)
        else
          check_new_game
          back_to_index and return
        end
      elsif @current_game.challenge_round?
        @challenge = Challenge::get_ongoing_challenge_by_game(@current_game.id)
        if @challenge
          if @challenge.valid_challenge?
            challenge_result = @challenge.apply_question_result(current_user.id, result, @current_game.bonus)
            if challenge_result == Challenge::RESULT_OPPONENT_TURN
              @current_game.increase_turn_count
              @current_game.end_round(current_user.id)
              back_to_index and return
            elsif challenge_result == Challenge::RESULT_TIE && current_user.id == @challenge.opponent_id
              @current_game.bonus = Game::BONUS_TRUE
              @current_game.save!
              ask_another_question(@current_game.id)
            elsif challenge_result == Challenge::RESULT_WINNER
              @current_game.apply_challenge_results(challenge_result, @challenge.challenger_id, @challenge.winner_id, @challenge.wager, @challenge.prize)
              notify_challenge_outcome(@challenge)
              @current_game.end_challenge(@challenge)
              @current_game.increase_turn_count
              @current_game.end_round(current_user.id)
              if @current_game.finished?
                notify_game_outcome(@current_game)
              end
              back_to_index and return
            else
              ask_another_question(@current_game.id)
            end
          else
            redirect_to game_challenge_path(:game_id => @current_game.id)
          end
        else
          redirect_to game_challenge_path(:game_id => @current_game.id)
        end
      end
    else
      back_to_index
    end
  end

  def check_new_game
    if @current_game.turn_count == 1 && current_user == @current_game.player1 && !@current_game.player1_turn?
      UserMailer.new_game_email(@current_game.player2, @current_game).deliver
    end
  end

  # pops the modal for the question
  def ask_question
    @game_id = params[:game_id]
    @current_game = Game.find(@game_id)
    @bonus = params[:bonus]
    unless @current_game.players_turn?(current_user.id)
      back_to_index and return
    end

    if @current_game.normal_round?
      subject_title = params[:subject]
      @subject = subject_title
      @questions = Question.questions_by_user_experience(current_user.experience_level, @subject)
      @question = @questions.sample
    elsif @current_game.challenge_round?
      @challenge = Challenge::get_ongoing_challenge_by_game(@current_game.id)
      if @challenge
        @question = Question.find(@challenge.get_question_id_by_counter)
        @subject = @question.subject_title
      elsif @challenge.nil?
        wager = params[:wager]
        prize = params[:prize]
        if wager && prize
          @challenge = Challenge.create_challenge(@current_game.id, current_user.id, @current_game.opponent_id(current_user.id), wager, prize)
        else
          redirect_to game_challenge_path(:game_id => @current_game.id)
        end
      end
    end
    if @question
      respond_to do |format|
        format.html
        format.xml { render :xml => @question }
      end
    end
  end

  def merit
    # needed for merit to be able to give power_ups
  end

  def use_power_up_skip_question
    current_user.use_skip_question
  end

  def use_power_up_remove_wrong_answer
    current_user.use_remove_wrong_answer
  end

  def use_power_up_extra_time
    current_user.use_extra_time
  end

  ############################################################
  #####################     PRIVATE     ######################
  ############################################################

  # checks params for new game MUST UPDATE!!!
  private

  def notify_game_outcome(game)
    if game.winner_id == current_user.id
      flash.alert = 'You won the game!'
    else
      flash.alert = game.opponent(current_user.id).name + ' won the game.'
    end
  end

  def notify_challenge_outcome(challenge)
    won_notice = 'You won the challenge!'
    lost_notice = 'You lost the challenge.'
    if challenge.winner_id == current_user.id
      flash.notice = won_notice
    else
      flash.notice = lost_notice
    end
  end

  def check_question_result(result)
    case result
      when User::NEW_LEVEL
        flash.notice = 'You leveled up!'
      when Merit::BadgeRules::BEGINNER
        flash.notice = 'You achieved ' + Merit::BadgeRules::BEGINNER + ' experience level!'
      when Merit::BadgeRules::INTERMEDIATE
        flash.notice = 'You achieved ' + Merit::BadgeRules::INTERMEDIATE + ' experience level!'
      when Merit::BadgeRules::ADVANCED
        flash.notice = 'You achieved ' + Merit::BadgeRules::ADVANCED + ' experience level!'
      when Merit::BadgeRules::EXPERT
        flash.notice = 'You achieved ' + Merit::BadgeRules::EXPERT + ' experience level!'
    end
  end

  def back_to_game(game_id)
    redirect_to '/game/game?game_id=' + game_id.to_s
  end

  def back_to_index
    redirect_to '/game/index'
  end

  def ask_another_question(game_id)
    redirect_to '/game/ask_question?game_id=' + game_id.to_s
  end

  def game_params
    params.require(:game).permit(player1_id: current_user.id, player2_id: @player2.id)
  end

  def answer_from_bonus?(flag)
    flag
  end

  def challenge
    @game_id = params[:game_id]
    redirect_to 'game/challenge'
  end

  def question_rating
    result = params[:result]
    subject = params[:subject]
    game_id = params[:game_id]
    bonus = params[:bonus]
    question_id = params[:question_id]
    rating = params[:rating]

    @question = Question.find(question_id)

app/helpers/game_helper.rb
module GameHelper
  EXTRA_TIME_ICON = 'fa fa-clock-o'
  REMOVE_WRONG_ANSWERS_ICON = 'fa fa-question-circle'
  SKIP_QUESTION_ICON = 'fa fa-arrow-circle-right'
end

app/views/game/_answers_correct.html.erb
<% if @game.answers_correct.to_i.eql?(1) || @game.answers_correct.to_i.eql?(2) || @game.answers_correct.to_i.eql?(3) %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
      <i class="fa fa-check fa-stack-1x"></i>
    </li>
<% else %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
    </li>
<% end %>
<% if @game.answers_correct.to_i.eql?(2) || @game.answers_correct.to_i.eql?(3) %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
      <i class="fa fa-check fa-stack-1x"></i>
    </li>
<% else %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
    </li>
<% end %>
<% if @game.answers_correct.to_i.eql?(3) %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
      <i class="fa fa-check fa-stack-1x"></i>
    </li>
<% else %>
    <li class="fa-stack fa-lg">
      <i class="fa fa-square-o fa-stack-2x"></i>
    </li>
<% end %>

app/views/game/ask_question.html.erb
<%
   game_id = @game_id
   subject = @subject
   question = @question
   bonus = @bonus
   answers = [question.rightAns, question.wrongAns1, question.wrongAns2, question.wrongAns3]
   answers = answers.shuffle
   wrong_answers = [question.wrongAns1, question.wrongAns2, question.wrongAns3]
   wrong_answers = wrong_answers.shuffle
   wrong_answer_one_index = answers.index(wrong_answers[0])
   wrong_answer_two_index = answers.index(wrong_answers[1])
   correct_answer_index = answers.index(question.rightAns)
   correct_ans = answers.index(question.rightAns)
%>

<html>
<%= stylesheet_link_tag "game.css.scss", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "jquery.progressTimer" %>
<%= javascript_include_tag "ask_question.js" %>

<header style="background-color: lightblue; padding-top: 3%">

  <div style="display: none;">
    <p id="correct_ans"><%= correct_ans %></p>

    <p id="correct_answer_index"><%= correct_answer_index %></p>

    <p id="game_id"><%= game_id %></p>

    <p id="subject"><%= subject %></p>

    <p id="bonus"><%= bonus %></p>

    <p id="question_id"><%= question.id %></p>

    <p id="play_sounds"><%= current_user.play_sounds %></p>

    <p id="wrong_answer_1_index"><%= wrong_answer_one_index %></p>

    <p id="wrong_answer_2_index"><%= wrong_answer_two_index %></p>
  </div>

  <audio id="ticktock" loop>
    <source src="/assets/tick_tock.mp3" type="audio/mpeg">
    <source src="/assets/tick_tock.ogg" type="audio/ogg">
  </audio>
  <audio id="wrong">
    <source src="/assets/wrong.mp3" type="audio/mpeg">
    <source src="/assets/wrong.ogg" type="audio/ogg">
  </audio>

  <audio id="right">
    <source src="/assets/right.mp3" type="audio/mpeg">
    <source src="/assets/right.ogg" type="audio/ogg">
  </audio>


  <script type="text/javascript">
      var timerSound = document.getElementById("ticktock");
      var wrongSound = document.getElementById("wrong");
      var rightSound = document.getElementById("right");
      var sound = document.getElementById("play_sounds").innerHTML;
      if (sound == "false") {
          timerSound.muted = true;
          wrongSound.muted = true;
          rightSound.muted = true;
      }
  </script>

</header>

<body style="margin-left: auto; margin-right: auto; text-align: center; align-content: center;">
<% if current_user.admin? %>
    <table class="table-condensed">
      <thead>
      <tr>
        <th>Game Attribute</th>
        <th>Value</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Answers Correct:</td>
        <td><%= @current_game.answers_correct.to_s %></td>
      </tr>
      <tr>
        <td>Game Challenge:</td>
        <td><%= @current_game.challenge %></td>
      </tr>
      <tr>
        <td>Game Bonus:</td>
        <td><%= @current_game.bonus %></td>
      </tr>
      </tbody>
    </table>
<% if @challenge %>
    <table>
      <thead>
      <tr>
        <th>Challenge Attribute</th>
        <th>Value</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Challenger Correct:</td>
        <td><%= @challenge.challenger_correct %></td>
      </tr>
      <tr>
        <td>Opponent Correct:</td>
        <td><%= @challenge.opponent_correct %></td>
      </tr>
      <tr>
        <td>Counter:</td>
        <td><%= @challenge.counter %></td>
      </tr>
      <tr>
        <td>Wager:</td>
        <td><%= @challenge.wager %></td>
      </tr>
      <tr>
        <td>Prize:</td>
        <td><%= @challenge.prize %></td>
      </tr>
      </tbody>
    </table>
<% end %>
<% end %>

<div class="container-fluid" id="question_container" style="margin-left: auto; margin-right: auto; text-align: center; align-content: center; padding-top: 2%;">
  <div class="row">
    <div class="col-xs-1 col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-8">

      <div id="progressTimer"></div>

      <h2><span class="label label-warning" id="qid"><%= @question.subject_title %></span>

        <h2 class="questionTitle" style="padding: 1%;"><%= @question.title %></h2>
      </h2>

      <div class="col-xs-3 col-xs-offset-5">
        <div id="loadbar" style="display: none;">
          <div class="blockG" id="rotateG_01"></div>
          <div class="blockG" id="rotateG_02"></div>
          <div class="blockG" id="rotateG_03"></div>
          <div class="blockG" id="rotateG_04"></div>
          <div class="blockG" id="rotateG_05"></div>
          <div class="blockG" id="rotateG_06"></div>
          <div class="blockG" id="rotateG_07"></div>
          <div class="blockG" id="rotateG_08"></div>
        </div>
      </div>

      <div class="quiz" id="quiz" data-toggle="buttons">
        <% if current_user.admin %>
            <p>Correct Answer: <%= question.rightAns %></p>
        <% end %>

        <label class="element-animation1 btn btn-lg btn-primary btn-block" id="first_answer"><span class="btn-label"></span>
          <input type="radio" name="q_answer" value="0"><%= answers[0] %></label>
        <label class="element-animation2 btn btn-lg btn-primary btn-block" id="second_answer"><span class="btn-label"></span>
          <input type="radio" name="q_answer" value="1"><%= answers[1] %></label>
        <label class="element-animation3 btn btn-lg btn-primary btn-block" id="third_answer"><span class="btn-label"></span>
          <input type="radio" name="q_answer" value="2"><%= answers[2] %></label>
        <label class="element-animation4 btn btn-lg btn-primary btn-block" id="fourth_answer"><span class="btn-label"></span>
          <input type="radio" name="q_answer" value="3"><%= answers[3] %></label>
      </div>

      <% if @current_game.normal_round? %>

          <span id="answer"></span>

          <div class="container" aria-label="..." style="padding-top: 2%;">
            <% if current_user.has_extra_time? %>
                <%= link_to game_use_power_up_extra_time_path(:user_id => current_user.id), class: 'btn btn-primary btn', id: 'time', title: 'Extra Time', remote: true do %>
                    Time
                <% end %>
            <% end %>

            <% if current_user.has_remove_wrong_answers? %>

                <%= link_to game_use_power_up_remove_wrong_answer_path(:user_id => current_user.id), class: 'btn btn-primary btn', id: 'half', title: 'Remove Answers', remote: true do %>
                    50/50
                <% end %>
            <% end %>

            <% if current_user.has_skip_question? %>
                <%= link_to game_use_power_up_skip_question_path(:user_id => current_user.id), class: 'btn btn-primary btn', id: 'skip', title: 'Skip', remote: true do %>
                    Skip
                <% end %>
            <% end %>

          </div>
      <% end %>
    </div>
  </div>
</div>



<!-- Question Rating Modal   -->
<div class="modal fade" id="rate_question" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

        <h2 class="modal-title">Question Rating</h2>
      </div>

      <h1><div id="result"></div></h1>

      <div class="modal-body">
        <p>Please Rate The Question Difficulty</p>

        <select id="rating" class="form-control">
          <option value="none" style="width: 150px; margin-left: 2px; margin-bottom: 2px;">Select Rating or Continue to Skip
          </option>
          <option value="easy" style="width: 150px; margin-left: 2px; margin-bottom: 2px;">
            Low Difficulty
          </option>
          <option value="medium" style="width: 150px; margin-left: 2px; margin-bottom: 2px;">
            Medium Difficulty
          </option>
          <option value="hard" style="width: 150px; margin-left: 2px; margin-bottom: 2px;">
            Hard Difficulty
          </option>
        </select>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="submit_rating" data-dismiss="modal">Continue</button>
      </div>

    </div>
    <div class="col-xs-1 col-sm-1 col-md-2 col-lg-2"></div>
  </div>
</div>

<script>
    loadTimerBar();
</script>

</body>
</html>

app/views/game/index.html.erb
<head>
  <%= stylesheet_link_tag "rules", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>

<body>
<br/>
<br/>

<!-- Name tied to ID for current user  -->
<div class="container-fluid" style="margin-bottom: 3%">
  <div class="row">
    <div class="col-xs-10 col-sm-12 col-md-12 col-lg-12">
      <ul class="nav nav-pills nav-justified thumbnail">
        <li class="active"><a href="#">
          <h1 class="list-group-item-heading"><%= current_user.name %></h1>


        </a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid" id="paypal_group" style="padding-bottom: 2%;">
  <div class="row">
    <div class="col-xs-10 col-sm-12 col-md-12 col-lg-12">

      <div class="col-xs-10 col-sm-3 col-md-2 col-lg-4">
        <%= link_to game_new_path(:id => 0, :game_id => 0, :player2_id => Game.random_player.id), class: 'btn btn-primary btn-lg', id: 'cont-btn', title: 'Play Random User'  do %>
            Play Random User
        <% end %>
      </div>

      <div class="col-xs-10 col-sm-6 col-md-4 col-lg-4">
        <%= form_tag statistics_index_path, :method => 'get' do %>
            <%= search_field_tag :search, params[:search], placeholder: 'Enter a name here' %>
            <%= submit_tag "Search for Player", :name => nil, class: 'btn btn-primary btn-lg' %>
        <% end %>
      </div>


      <div class="col-xs-10 col-sm-3 col-md-2 col-lg-4">
        <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#paypal_modal" style="float: right;">
          Buy More Coins!
        </button>
      </div>

    </div>
  </div>

</div>
</body>

<a href="#" class="list-group-item active">
  <h4>Active Games</h4>
</a>

<div class="list-group">
  <% if @active_games.any? %>

      <% @active_games.each do |game| %>

              <li class="list-group-item" >
                <% if game.players_turn?(current_user.id) %>
                    <h5 class="list-group-item-heading">Playing: <%=game.opponent(current_user.id).name + ".  " %>It's your turn.</h5>
                    <%= link_to game_game_path(:game_id => game.id, :player2_id => game.player2_id), class: 'btn btn-primary btn', id: 'cont-btn', title: 'Continue Game' do %>
                        Continue Game
                    <% end %>

                <% else %>
                    <h5 class="list-group-item-heading">It's <%= game.opponent(current_user.id).name %>'s turn.</h5>
                <% end %>
                <%= link_to game_end_game_path(:game_id => game.id), class: 'btn btn-danger btn', id: 'end-btn', title: 'End Game',
                            :data => {:confirm => 'Forfeiting a game counts as a loss. Are you sure?'} do %>
                    End Game
                <% end %>

              </li>

      <% end %>
  <% else %>
      <h4>You have no active games.</h4>
  <% end %>
</div>

<!-- gets finished games for current user onclick  -->
<div class="list-group">
  <a href="#" class="list-group-item active">
    <h4>Completed Games</h4>
  </a>
  <% if @finished_games.any? %>
      <% @finished_games.each do |game| %>

              <a href="#" class="list-group-item"><%= "Player 1: " + game.player1.name + ",  Player 2: " + game.player2.name + ", Winner: " + User.find(game.winner_id).name %></a>
          <% end %>
      <% else %>

      <h4>You have no completed games.</h4>
  <% end %>
</div>


<!-- Gets a list of all users returns list minus current user  -->

<!--   List of all users ove to index page after all project goals are met

<div class="list-group">
  <a href="#" class="list-group-item active">
    <h4>All Users</h4>
  </a>

  <% @playable_users.each do |player2| %>
      <li class="list-group-item">
        <span class="btn btn-large" style="float: right">
        <%= link_to game_game_path(:player2_id => player2.id, :game_id => 0), class: 'btn btn-primary btn', id: 'cont-btn', title: 'Play New Game' do %>
            Play New Game
        <% end %>
        </span>
        <%= player2.name %>
      </li>
  <% end %>
</div>


-->



<div class="modal fade" id="paypal_modal" tabindex="-1" role="dialog" aria-labelledby="subject_modal_label" aria-hidden="true" data-backdrop="static" data-keyboard="false" style="align-content: center;">
  <div class="modal-dialog">
    <div class="modal-content " style=" border: 2px solid darkblue; background: lightblue">


      <div class="modal-body">

        <div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
          <label class="fa fa-cart-plus fa-2x">&nbsp;&nbsp; 10 Coins<br/>$.99 </label>

          <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="FK4LZX7P8XSKE">
            <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
        </div>



        <div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
          <label class="fa fa-cart-plus fa-2x">&nbsp; 50 Coins<br/>$4.49 </label>

          <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="P4D3XKW4LF9R8">
            <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
        </div>



        <div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
          <label class="fa fa-cart-plus fa-2x"> 100 Coins<br/>$8.49 </label>

          <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="2QKDGH8N2XCNJ">
            <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
          <p>
            <button type="button" class="btn btn-danger" data-dismiss="modal" style="float: right;" >Cancel</button>
          </p>
        </div>

      </div>   <!-- modal body -->


      <div class="modal-footer">

      </div>

    </div>
  </div>
</div>

app/views/game/welcome.html.erb
<h1>Welcome to SnapTrivia</h1>

<%= link_to 'GamePage', game_index_path %> <br>
<%= link_to 'GameRules', game_rules_path %>