config/routes.rb
Snaptrivia::Application.routes.draw do

  resources :questions, :subjects, :messages

  get 'game_home/gameHome'
  get 'questions/new'
  get 'game/ask_question'
  get 'game/challenge'
  get 'game/index'
  get 'game/cancel_transaction'
  get 'game/success_transaction'
  get 'game/game' => 'game#game'
  get 'game/new'
  get 'game/question_results'
  get 'game/end_game'
  get 'game/use_power_up_skip_question'
  get 'game/use_power_up_remove_wrong_answer'
  get 'game/use_power_up_extra_time'
  get 'statistics/show'
  get 'statistics/index'

  get 'statistics/site_stats'

  get 'challenge/question_results', to: 'game#question_results'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "game/rules"
  get "game/welcome"

  devise_for :reviewers
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

   root 'game#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snaptrivia</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      <% if current_user.show_picture? %>
          <%= image_tag current_user.image %>
      <% end %>

      <% if current_user.name.nil? %>
          Logged in as <strong><%= current_user.email %></strong>.
      <% else %>
          Logged in as <strong><%= current_user.name %></strong>.
      <% end %>
      <%= link_to "Home", root_path %> |
      <% if current_user.admin || current_user.reviewer %>
          <%= link_to 'Dashboard', rails_admin.dashboard_path %> |
      <% end %>
      <%= link_to 'Profile/Settings', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to 'Submit Question', new_question_path, :class => 'navbar-link' %> |
      <%= link_to 'Inbox', messages_path  %> |
      <%= link_to 'Game Rules', game_rules_path %> |
      <%= link_to 'User Stats', statistics_show_path(:user_id => current_user.id) %> |
      <%= link_to 'Site Stats', statistics_site_stats_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %> |
      <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
  <% end %>

  <%= yield %>


  </body>
</html>